CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY ,
    PW VARCHAR2(100) NOT NULL,
    PWCHECK_QUESTION VARCHAR2(500) NOT NULL,
    PWCHECK_ANSWER VARCHAR2(500) NOT NULL,
    USER_NAME VARCHAR2(10) NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    POSTCODE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(100) NOT NULL,
    ADDRESS_EXTRA VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    REFERER VARCHAR2(20)
);

COMMIT;