CREATE TABLE MEMBER (
    ID VARCHAR(20) PRIMARY KEY ,
    PW NUMBER NOT NULL,
    PWCHECK_QUESTION VARCHAR(50) NOT NULL,
    PWCHECK_ANSWER VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(10) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    POSTCODE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    ADDRESS_DETAIL VARCHAR(100) NOT NULL,
    ADDRESS_EXTRA VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    REFERER VARCHAR(20)
);

COMMIT;